### ISSUE TITLE
Quirky initial entry into date field

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-markdown-halogen#8]
This ticket on SlamData (https://github.com/slamdata/slamdata/issues/419) probably belongs here...

When a date input field is rendered (in Chrome), trying to input a date via the keyboard results in a strange effect. Whichever is the last segment of the input field that you edit (e.g. day, month or year), that segment is cleared after you enter your first digit. So, if I try to type `07301992` in order to write in my birthday, the result is `07/30/00992` or something along those lines.

Gary has proposed that this may be due to an unfortunate side effect of the virtual-dom use. I am not familiar enough with virtual-dom to say definitively whether this is the case, but it sounds very plausible based on his proposed explanation.

**Comment by garyb** [comment]
I think we can close this now?
